// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// HT_cpp
Rcpp::List HT_cpp(Eigen::MatrixXd X, Eigen::VectorXd y);
RcppExport SEXP _sublime_HT_cpp(SEXP XSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(HT_cpp(X, y));
    return rcpp_result_gen;
END_RCPP
}
// kBOSS
Rcpp::List kBOSS(Eigen::MatrixXd& X, Eigen::VectorXd& y, Rcpp::NumericVector freqs, int k_iboss);
RcppExport SEXP _sublime_kBOSS(SEXP XSEXP, SEXP ySEXP, SEXP freqsSEXP, SEXP k_ibossSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freqs(freqsSEXP);
    Rcpp::traits::input_parameter< int >::type k_iboss(k_ibossSEXP);
    rcpp_result_gen = Rcpp::wrap(kBOSS(X, y, freqs, k_iboss));
    return rcpp_result_gen;
END_RCPP
}
// kmeans2
Rcpp::NumericVector kmeans2(Rcpp::NumericVector& freq_count);
RcppExport SEXP _sublime_kmeans2(SEXP freq_countSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type freq_count(freq_countSEXP);
    rcpp_result_gen = Rcpp::wrap(kmeans2(freq_count));
    return rcpp_result_gen;
END_RCPP
}
// SRHT_cpp
Rcpp::List SRHT_cpp(Eigen::MatrixXd X, Eigen::VectorXd y, int r);
RcppExport SEXP _sublime_SRHT_cpp(SEXP XSEXP, SEXP ySEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(SRHT_cpp(X, y, r));
    return rcpp_result_gen;
END_RCPP
}
// geniboss_cpp
Rcpp::List geniboss_cpp(const Eigen::MatrixXd& A, const Eigen::MatrixXd& X, const Eigen::VectorXd& y, int r);
RcppExport SEXP _sublime_geniboss_cpp(SEXP ASEXP, SEXP XSEXP, SEXP ySEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(geniboss_cpp(A, X, y, r));
    return rcpp_result_gen;
END_RCPP
}
// iboss_cpp
Rcpp::List iboss_cpp(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, int k, bool intercept, bool add_logs);
RcppExport SEXP _sublime_iboss_cpp(SEXP XSEXP, SEXP ySEXP, SEXP kSEXP, SEXP interceptSEXP, SEXP add_logsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type intercept(interceptSEXP);
    Rcpp::traits::input_parameter< bool >::type add_logs(add_logsSEXP);
    rcpp_result_gen = Rcpp::wrap(iboss_cpp(X, y, k, intercept, add_logs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sublime_HT_cpp", (DL_FUNC) &_sublime_HT_cpp, 2},
    {"_sublime_kBOSS", (DL_FUNC) &_sublime_kBOSS, 4},
    {"_sublime_kmeans2", (DL_FUNC) &_sublime_kmeans2, 1},
    {"_sublime_SRHT_cpp", (DL_FUNC) &_sublime_SRHT_cpp, 3},
    {"_sublime_geniboss_cpp", (DL_FUNC) &_sublime_geniboss_cpp, 4},
    {"_sublime_iboss_cpp", (DL_FUNC) &_sublime_iboss_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_sublime(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
