# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_featuresrht_wrapper <- function(X, y, X_test_in, y_test_in, r, bins, alpha, run_uni, run_top, run_lev, run_sup) {
    .Call(`_class_run_featuresrht_wrapper`, X, y, X_test_in, y_test_in, r, bins, alpha, run_uni, run_top, run_lev, run_sup)
}

endPart <- function(nLASSO_K, nC, m, p, freq_count) {
    .Call(`_class_endPart`, nLASSO_K, nC, m, p, freq_count)
}

HT_cpp <- function(X, y) {
    .Call(`_class_HT_cpp`, X, y)
}

kBOSS <- function(X, y, freqs, k_iboss) {
    .Call(`_class_kBOSS`, X, y, freqs, k_iboss)
}

kmeans2 <- function(freq_count) {
    .Call(`_class_kmeans2`, freq_count)
}

SRHT_cpp <- function(X, y, r) {
    .Call(`_class_SRHT_cpp`, X, y, r)
}

geniboss_cpp <- function(A, X, y, r) {
    .Call(`_class_geniboss_cpp`, A, X, y, r)
}

iboss_cpp <- function(X, y, k, intercept, add_logs) {
    .Call(`_class_iboss_cpp`, X, y, k, intercept, add_logs)
}

fast_subsample <- function(X, y, nSample) {
    .Call(`_class_fast_subsample`, X, y, nSample)
}

r2 <- function(y_true, y_pred) {
    .Call(`_class_r2`, y_true, y_pred)
}

MSE <- function(y_true, y_pred) {
    .Call(`_class_MSE`, y_true, y_pred)
}

betaOLS_closed <- function(X, y) {
    .Call(`_class_betaOLS_closed`, X, y)
}

