# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HT_cpp <- function(X, y) {
    .Call(`_sublime_HT_cpp`, X, y)
}

kBOSS <- function(X, y, freqs, k_iboss) {
    .Call(`_sublime_kBOSS`, X, y, freqs, k_iboss)
}

kmeans2 <- function(freq_count) {
    .Call(`_sublime_kmeans2`, freq_count)
}

SRHT_cpp <- function(X, y, r) {
    .Call(`_sublime_SRHT_cpp`, X, y, r)
}

geniboss_cpp <- function(A, X, y, r) {
    .Call(`_sublime_geniboss_cpp`, A, X, y, r)
}

iboss_cpp <- function(X, y, k, intercept, add_logs) {
    .Call(`_sublime_iboss_cpp`, X, y, k, intercept, add_logs)
}

